version: '3.7'

services:
  movie_service:
    build: ./movie_service
    container_name: fastapi
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./movie_service/:/app/
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=postgresql://movie_user:movie_password@movie_db:5432/pgmovie_db
    depends_on:
      - movie_db
  
  movie_db:
    image: postgres:12.1-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres_data_movie:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=movie_user
      - POSTGRES_PASSWORD=movie_password
      - POSTGRES_DB=pgmovie_db
